-- Aktimetrix tables. Created at startup unless aktimetrix.storage.create-indexes=false; every statement is idempotent.
-- Each row keeps the object as a JSON document, next to the columns that queries, constraints and version checks use.
CREATE TABLE IF NOT EXISTS aktimetrix_process_definition (
    id           VARCHAR(64)  PRIMARY KEY,
    tenant       VARCHAR(255) NOT NULL,
    process_code VARCHAR(255) NOT NULL,
    status       VARCHAR(64),
    document     TEXT         NOT NULL,
    CONSTRAINT aktimetrix_process_definition_code UNIQUE (tenant, process_code)
);
CREATE TABLE IF NOT EXISTS aktimetrix_step_definition (
    id        VARCHAR(64)  PRIMARY KEY,
    tenant    VARCHAR(255) NOT NULL,
    step_code VARCHAR(255) NOT NULL,
    document  TEXT         NOT NULL,
    CONSTRAINT aktimetrix_step_definition_code UNIQUE (tenant, step_code)
);
CREATE TABLE IF NOT EXISTS aktimetrix_measurement_type (
    id       VARCHAR(64) PRIMARY KEY,
    tenant   VARCHAR(255),
    type_code VARCHAR(255),
    document TEXT        NOT NULL
);
CREATE TABLE IF NOT EXISTS aktimetrix_process_instance (
    id           VARCHAR(64)  PRIMARY KEY,
    tenant       VARCHAR(255) NOT NULL,
    process_code VARCHAR(255) NOT NULL,
    entity_type  VARCHAR(255),
    entity_id    VARCHAR(255) NOT NULL,
    status       VARCHAR(32),
    complete     BOOLEAN      NOT NULL,
    late_after   TIMESTAMP,
    timeliness   VARCHAR(16),
    revision     BIGINT       NOT NULL,
    run_number   INTEGER      DEFAULT 1 NOT NULL,
    document     TEXT         NOT NULL
);
-- one instance per run of a process for an entity; upgrades a table that had one instance per entity
ALTER TABLE aktimetrix_process_instance ADD COLUMN IF NOT EXISTS run_number INTEGER DEFAULT 1 NOT NULL;
ALTER TABLE aktimetrix_process_instance DROP CONSTRAINT IF EXISTS aktimetrix_process_entity;
CREATE UNIQUE INDEX IF NOT EXISTS aktimetrix_process_entity_run
    ON aktimetrix_process_instance (tenant, process_code, entity_type, entity_id, run_number);
CREATE INDEX IF NOT EXISTS aktimetrix_process_by_entity ON aktimetrix_process_instance (tenant, entity_id);
CREATE INDEX IF NOT EXISTS aktimetrix_process_deadlines ON aktimetrix_process_instance (late_after, complete);
CREATE TABLE IF NOT EXISTS aktimetrix_step_instance (
    id                  VARCHAR(64)  PRIMARY KEY,
    tenant              VARCHAR(255) NOT NULL,
    process_instance_id VARCHAR(64)  NOT NULL,
    step_sequence       INT          NOT NULL,
    status              VARCHAR(32),
    late_after          TIMESTAMP,
    timeliness          VARCHAR(16),
    revision            BIGINT       NOT NULL,
    document            TEXT         NOT NULL
);
CREATE INDEX IF NOT EXISTS aktimetrix_steps_by_process ON aktimetrix_step_instance (tenant, process_instance_id);
CREATE INDEX IF NOT EXISTS aktimetrix_step_deadlines ON aktimetrix_step_instance (late_after, status);
CREATE TABLE IF NOT EXISTS aktimetrix_measurement_instance (
    id                  VARCHAR(64)  PRIMARY KEY,
    row_order           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant              VARCHAR(255) NOT NULL,
    process_instance_id VARCHAR(64)  NOT NULL,
    step_instance_id    VARCHAR(64),
    measurement_code    VARCHAR(255),
    measurement_type    VARCHAR(8),
    document            TEXT         NOT NULL
);
CREATE INDEX IF NOT EXISTS aktimetrix_measurements_by_process ON aktimetrix_measurement_instance (tenant, process_instance_id);
CREATE TABLE IF NOT EXISTS aktimetrix_outbox (
    id           VARCHAR(64)  PRIMARY KEY,
    row_order    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    destination  VARCHAR(255) NOT NULL,
    message_key  VARCHAR(255),
    payload      TEXT         NOT NULL,
    created_at   BIGINT       NOT NULL,
    sent_at      BIGINT,
    locked_until BIGINT,
    attempts     INT          NOT NULL
);
CREATE INDEX IF NOT EXISTS aktimetrix_outbox_pending ON aktimetrix_outbox (sent_at, created_at);
CREATE TABLE IF NOT EXISTS aktimetrix_alarm (
    id                  VARCHAR(80)  PRIMARY KEY,
    tenant              VARCHAR(255) NOT NULL,
    kind                VARCHAR(16)  NOT NULL,
    target_id           VARCHAR(64)  NOT NULL,
    process_instance_id VARCHAR(64),
    due_at              TIMESTAMP    NOT NULL,
    locked_until        BIGINT,
    attempts            INT          NOT NULL
);
CREATE INDEX IF NOT EXISTS aktimetrix_alarms_due ON aktimetrix_alarm (due_at);
CREATE TABLE IF NOT EXISTS aktimetrix_processed_event (
    tenant       VARCHAR(255) NOT NULL,
    event_id     VARCHAR(255) NOT NULL,
    processed_at BIGINT       NOT NULL,
    PRIMARY KEY (tenant, event_id)
);
CREATE INDEX IF NOT EXISTS aktimetrix_processed_events_at ON aktimetrix_processed_event (processed_at);
