-- Aktimetrix tables. Created at startup unless aktimetrix.storage.create-indexes=false; every statement is idempotent.
-- Each row keeps the object as a JSON document, next to the columns that queries, constraints and version checks use.
CREATE TABLE IF NOT EXISTS aktimetrix_process_definition (
    id           VARCHAR(64)  PRIMARY KEY,
    tenant       VARCHAR(255) NOT NULL,
    process_code VARCHAR(255) NOT NULL,
    status       VARCHAR(64),
    document     TEXT         NOT NULL,
    CONSTRAINT aktimetrix_process_definition_code UNIQUE (tenant, process_code)
);
CREATE TABLE IF NOT EXISTS aktimetrix_step_definition (
    id        VARCHAR(64)  PRIMARY KEY,
    tenant    VARCHAR(255) NOT NULL,
    step_code VARCHAR(255) NOT NULL,
    document  TEXT         NOT NULL,
    CONSTRAINT aktimetrix_step_definition_code UNIQUE (tenant, step_code)
);
CREATE TABLE IF NOT EXISTS aktimetrix_measurement_type (
    id       VARCHAR(64) PRIMARY KEY,
    tenant   VARCHAR(255),
    type_code VARCHAR(255),
    document TEXT        NOT NULL
);
CREATE TABLE IF NOT EXISTS aktimetrix_process_instance (
    id           VARCHAR(64)  PRIMARY KEY,
    tenant       VARCHAR(255) NOT NULL,
    process_code VARCHAR(255) NOT NULL,
    entity_type  VARCHAR(255),
    entity_id    VARCHAR(255) NOT NULL,
    status       VARCHAR(32),
    complete     BOOLEAN      NOT NULL,
    late_after   TIMESTAMP,
    timeliness   VARCHAR(16),
    revision     BIGINT       NOT NULL,
    document     TEXT         NOT NULL,
    CONSTRAINT aktimetrix_process_entity UNIQUE (tenant, process_code, entity_type, entity_id)
);
CREATE INDEX IF NOT EXISTS aktimetrix_process_by_entity ON aktimetrix_process_instance (tenant, entity_id);
CREATE INDEX IF NOT EXISTS aktimetrix_process_deadlines ON aktimetrix_process_instance (late_after, complete);
CREATE TABLE IF NOT EXISTS aktimetrix_step_instance (
    id                  VARCHAR(64)  PRIMARY KEY,
    tenant              VARCHAR(255) NOT NULL,
    process_instance_id VARCHAR(64)  NOT NULL,
    step_sequence       INT          NOT NULL,
    status              VARCHAR(32),
    late_after          TIMESTAMP,
    timeliness          VARCHAR(16),
    revision            BIGINT       NOT NULL,
    document            TEXT         NOT NULL
);
CREATE INDEX IF NOT EXISTS aktimetrix_steps_by_process ON aktimetrix_step_instance (tenant, process_instance_id);
CREATE INDEX IF NOT EXISTS aktimetrix_step_deadlines ON aktimetrix_step_instance (late_after, status);
CREATE TABLE IF NOT EXISTS aktimetrix_measurement_instance (
    id                  VARCHAR(64)  PRIMARY KEY,
    row_order           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant              VARCHAR(255) NOT NULL,
    process_instance_id VARCHAR(64)  NOT NULL,
    step_instance_id    VARCHAR(64),
    measurement_code    VARCHAR(255),
    measurement_type    VARCHAR(8),
    document            TEXT         NOT NULL
);
CREATE INDEX IF NOT EXISTS aktimetrix_measurements_by_process ON aktimetrix_measurement_instance (tenant, process_instance_id);
CREATE TABLE IF NOT EXISTS aktimetrix_outbox (
    id           VARCHAR(64)  PRIMARY KEY,
    row_order    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    destination  VARCHAR(255) NOT NULL,
    message_key  VARCHAR(255),
    payload      TEXT         NOT NULL,
    created_at   BIGINT       NOT NULL,
    sent_at      BIGINT,
    locked_until BIGINT,
    attempts     INT          NOT NULL
);
CREATE INDEX IF NOT EXISTS aktimetrix_outbox_pending ON aktimetrix_outbox (sent_at, created_at);
