server:
  port: '7070'
spring:
  application:
    name: processor
  data:
    mongodb:
      database: svm
      uri: mongodb://localhost:27017,localhost:27018,localhost:27019
  jackson:
    serialization:
      write-dates-as-timestamps: false
  #    default-property-inclusion: always, non_null, non_absent, non_default, non_empty

  cloud:
    stream:
      bindings:
        processor-in-0:
          group: processor.cargo.group.0
      source: process-instance;step-instance
      kafka:
        bindings:
          process-instance-out-0:
            producer:
              configuration:
                "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
          step-instance-out-0:
            producer:
              configuration:
                "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    com.aktimetrix: DEBUG
