server:
  port: '6060'
spring:
  application:
    name: planner
  data:
    mongodb:
      database: planner
      uri: 'mongodb://localhost:27017,localhost:27018,localhost:27019'
  jackson:
    serialization:
      write-dates-as-timestamps: false
  cloud:
    function:
      definition: stepConsumer;processConsumer;measurementConsumer
    stream:
      function:
        bindings:
          stepConsumer-in-0: step
          processConsumer-in-0: process
          measurementConsumer-in-0: measurement
      bindings:
        step:
          destination: step-instance-out-0
          group: planner.step.group.0
        process:
          destination: process-instance-out-0
          group: planner.process.group.0
        measurement:
          destination: measurement-instance-out-0
          group: planner.measurement.group.0
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG
    com.aktimetrix.service.planner: DEBUG



