server:
  port: '9090'
spring:
  application:
    name: meter
  data:
    mongodb:
      database: meter
      uri: 'mongodb://localhost:27017,localhost:27018,localhost:27019'
  cloud:
    stream:
      function:
        bindings:
          measure-in-0: input
      bindings:
        input:
          group: meter.step.group.0
          destination: step-instance-out-0
      kafka:
        bindings:
          input:
            consumer:
              enableDlq: true
              dlqName: input-topic-dlq
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG
    com.aktimetrix.service.meter: DEBUG


