spring:
  application:
    name: meter
  data:
    mongodb:
      database: svm
      uri: 'mongodb://localhost:27017,localhost:27018,localhost:27019'

  cloud:
    stream:
      function:
        bindings:
          measure-in-0: input
      bindings:
        input:
          group: meter-group-0
          destination: step-instance-in-0

server:
  port: '9090'
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG
    com.aktimetrix.service.meter: DEBUG


